version: "3.9"
services:
  frontend:
    container_name: game-hub
    image: game-hub/v1.0.0
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - frontend
    ports:
      - "8080:80"
      
networks:
  frontend:
    name: game-hub